### ISSUE TITLE
Error msg when running aegit_Template_EXPORT

### ISSUE THREAD

**Issue by jzhu22** [peterennis/aegit_Template#6]
4.Open the module aebasTEST_aegit_expClass in the VBA editor
5.Run the command aegit_Template_EXPORT <-------

error msg: Erl=0 Error 2220(Microsoft Access can't open the file '.\src\xml\tables_aeItems_DataMacro.xml'.) in procedure Output TableDataMacros of Class aegit_expClass

**Comment by peterennis** [comment]
Showed up again in download zip to temp and extract all to the subfolder

**Comment by peterennis** [comment]
Fixed in v146
